# Generated by Django 4.1 on 2022-08-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='owed_by_Model',
        ),
        migrations.DeleteModel(
            name='owes_Model',
        ),
        migrations.DeleteModel(
            name='USer_Model',
        ),
    ]
