# Generated by Django 4.1 on 2022-08-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debt', '0002_delete_owed_by_model_delete_owes_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='owed_by_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Owed_by',
            },
        ),
        migrations.CreateModel(
            name='owes_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Owes',
            },
        ),
        migrations.CreateModel(
            name='USer_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debt.owed_by_model')),
                ('owes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debt.owes_model')),
            ],
            options={
                'verbose_name_plural': 'Users list',
            },
        ),
    ]
