# Generated by Django 4.1 on 2022-08-10 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='owed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debt.owed_by_model'),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='owes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debt.owes_model'),
        ),
    ]
