# Generated by Django 4.1 on 2022-08-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0004_alter_user_model_owed_by_alter_user_model_owes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='balance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
