# Generated by Django 4.1 on 2022-08-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0007_remove_user_model_owed_by_remove_user_model_owes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='owed_by',
            field=models.ManyToManyField(to='debt.owed_by_model'),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='owes',
            field=models.ManyToManyField(to='debt.owes_model'),
        ),
    ]
